---
title: Servicio de Asesoría Estadística
author: Eduardo Guamán
date: '2019-01-20'
tags:
  - Asesoría Estadística
output: blogdown::html_page
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

## Asesoría en:

* **Análisis descriptivo y exploratorio:** 
  - Tablas de frecuencias
  - Gráficos
  - Tablas de contingencia

* **Análisis estadístico inferencial:** 
  - Intervalos de confianza
  - Prueba de hipótesis para una, dos y más de dos muestras

+ **Análisis Multivariante:** 
Puesto que hay varias variables medidas para cada individuo ú objeto estudiado, es necesario acudir a las técnicas multivariantes:
  - análisis de regresión lineal múltiple,
  - análisis de clúster o agrupamiento,
  - análisis de componentes principales,
  - análisis de correspondencias múltiples,
  - análisis discriminante,
  - etc.

+ **Encuestas:** 
  - Diseño y planteamiento de encuestas
  - Análisis de datos generados por las encuestas

+ **Diseño Muestral:** 
  - __Muestreo Probabilístico__: Muestreo aleatorio simple, muestreo sistemático, muestreo estratificado, muestreo por conglomerados.
  - __Muestreo No Probabilístico__: Muestreo por cuotas, muestreo de bola de nieve, muestreo causal o incidental.
  - Determinar el tamaño muestral.

+ **Diseño de Experimentos:** 
  - Identificación y definición de variables.
  - Planeación del experimento.
  - Análisis del diseño experimental.
  
+ **Series de Tiempo:** 
  - Modelamiento y Pronósticos.

+ **Análisis de Supervivencia:** 
Técnicas que permiten estudiar la variable “tiempo hasta que ocurre un evento” y su dependencia de otras posibles variables explicatorias. Estos métodos generalmente se usan para estudios de mortalidad, o simplemente unidades que presentan un cambio de estado. Se realizan análisis descriptivos, análisis con el método de Kaplan-Meyer, modelos logísticos y modelos de cox.

+ **Métodos No Paramétricos:** 
Los métodos no paramétricos son útiles cuando no se cumple el supuesto de normalidad y el tamaño de la muestra es pequeño. Las principales pruebas no paramétricas son las siguientes:
  - Prueba χ² de Pearson
  - Prueba binomial
  - Prueba de Anderson-Darling
  - Prueba de Cochran
  - Prueba de Cohen kappa
  - Prueba de Fisher
  - Prueba de Friedman
  - Prueba de Kendall
  - Prueba de Kolmogórov-Smirnov
  - Prueba de Kruskal-Wallis
  - Prueba de Kuiper
  - Prueba de Mann-Whitney o prueba de Wilcoxon
  - Prueba de McNemar
  - Prueba de la mediana
  - Prueba de Siegel-Tukey
  - Prueba de los signos
  - Coeficiente de correlación de Spearman
  - Tablas de contingencia
  - Prueba de Wald-Wolfowitz
  - Prueba de los rangos con signo de Wilcoxon

## Esto y mucho más solo contáctame, me encuentro en la Av. General Enríquez y Colombia (Sangolquí-Ec)

## Asesoro:

+ **Tesis, tesinas y otros trabajos de investigación**
+ **Publicaciones en revistas de investigación**
+ **Grupos de investigación e innovación**
+ **Soporte puntual en proyectos que requieran la colaboración de un estadístico profesional**

## Contacto:

* Correo: 
    * guamandseduardo@gmail.com
* Facebook:
    * [fb.com/guamandseduardo](https://www.facebook.com/guamandseduardo)
